cp theme/css/default.css ../01*/theme/css/default.css
cp theme/css/default.css ../02*/theme/css/default.css
cp theme/css/default.css ../03*/theme/css/default.css
cp theme/css/default.css ../04*/theme/css/default.css
cp theme/css/default.css ../05*/theme/css/default.css
cp theme/css/default.css ../06*/theme/css/default.css
cp theme/css/default.css ../07*/theme/css/default.css
cp theme/css/default.css ../08*/theme/css/default.css
cp theme/css/default.css ../09*/theme/css/default.css
cp theme/css/default.css ../10*/theme/css/default.css
cp theme/css/default.css ../11*/theme/css/default.css
cp theme/css/default.css ../12*/theme/css/default.css
cp theme/css/default.css ../13*/theme/css/default.css
cp theme/css/default.css ../14*/theme/css/default.css
cp theme/css/default.css ../15*/theme/css/default.css
cp theme/css/default.css ../16*/theme/css/default.css
cp theme/css/default.css ../17*/theme/css/default.css
cp theme/css/default.css ../18*/theme/css/default.css
cp theme/css/default.css ../19*/theme/css/default.css
cp theme/css/default.css ../20*/theme/css/default.css
cp theme/css/default.css ../21*/theme/css/default.css
cp theme/css/default.css ../22*/theme/css/default.css
cp theme/css/default.css ../23*/theme/css/default.css
cp theme/css/default.css ../24*/theme/css/default.css
cp theme/css/default.css ../25*/theme/css/default.css
cp theme/css/default.css ../26*/theme/css/default.css
cp theme/css/default.css ../27*/theme/css/default.css
cp theme/css/default.css ../28*/theme/css/default.css